### ISSUE TITLE
[Post list] Crash opening an image

### ISSUE THREAD

**Issue by NicKoehler** [LiveFastEatTrashRaccoon/RaccoonForLemmy#188]
**Describe the bug**
The app crashes when I tap on an image

**To Reproduce**
1. Find a post with an image
2. Tap it
3. See crash

**Expected behavior**
Open the image in full screen

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 15 (Graphene OS) 
 - Version 1.13.5

**Crash log**

```
type: crash
osVersion: google/cheetah/cheetah:15/AP4A.241205.013/2024121200:user/release-keys
flags: dev options enabled
package: com.livefast.eattrash.raccoonforlemmy.android:133, targetSdk 35
process: com.livefast.eattrash.raccoonforlemmy.android
processUptime: 8927 + 255 ms
installer: dev.imranr.obtainium

Ab.Z1: No binding found for z tagged "https://i.imgur.com/oMGZXsr.png"
	at na.q.x(Unknown Source:1233)
	at na.q.K(Unknown Source:8)
	at o3.r.o(Unknown Source:33)
	at r8.p.n(Unknown Source:216)
	at G3.a.o(Unknown Source:23)
	at a0.a.f(Unknown Source:43)
	at a0.a.o(Unknown Source:8)
	at A.i0.k(Unknown Source:497)
	at a0.a.k(Unknown Source:51)
	at S.d.a(Unknown Source:226)
	at b0.h.c(Unknown Source:148)
	at A.i0.k(Unknown Source:682)
	at a0.a.k(Unknown Source:51)
	at A.k0.k(Unknown Source:43)
	at a0.a.k(Unknown Source:51)
	at A.k0.k(Unknown Source:78)
	at a0.a.k(Unknown Source:51)
	at S.d.b(Unknown Source:149)
	at A.L.k(Unknown Source:188)
	at a0.a.k(Unknown Source:51)
	at S.d.a(Unknown Source:226)
	at b0.h.c(Unknown Source:148)
	at o7.h.o(Unknown Source:121)
	at a0.a.f(Unknown Source:43)
	at a0.a.o(Unknown Source:8)
	at x3.f.o(Unknown Source:86)
	at a0.a.f(Unknown Source:43)
	at a0.a.o(Unknown Source:8)
	at v3.e.d(Unknown Source:32)
	at x3.e.c(Unknown Source:240)
	at x3.g.k(Unknown Source:42)
	at a0.a.k(Unknown Source:51)
	at O.V.k(Unknown Source:75)
	at a0.a.k(Unknown Source:51)
	at x3.c.d(Unknown Source:48)
	at x3.e.c(Unknown Source:196)
	at x3.e.b(Unknown Source:53)
	at C3.d.d(Unknown Source:241)
	at G3.c.o(Unknown Source:148)
	at a0.a.f(Unknown Source:43)
	at a0.a.o(Unknown Source:8)
	at E.x0.g(Unknown Source:151)
	at a0.a.a(Unknown Source:43)
	at a0.a.g(Unknown Source:8)
	at androidx.compose.animation.a.a(Unknown Source:1328)
	at s.e.k(Unknown Source:264)
	at a0.a.k(Unknown Source:51)
	at W0.e.b(Unknown Source:892)
	at W0.e.a(Unknown Source:185)
	at a.a.f(Unknown Source:149)
	at A.Q.k(Unknown Source:238)
	at S.p.E(Unknown Source:450)
	at S.p.K(Unknown Source:136)
	at S.p.n(Unknown Source:237)
	at S.p.D(Unknown Source:29)
	at S.t.u(Unknown Source:21)
	at S.s0.p(Unknown Source:104)
	at S.q0.b(Unknown Source:538)
	at D0.k0.doFrame(Unknown Source:33)
	at D0.i0.doFrame(Unknown Source:47)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1413)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1424)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1024)
	at android.view.Choreographer.doFrame(Choreographer.java:949)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1398)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: ya.e: [D0.l0@d1af987, D0.N0@1ed90b4, v0{Cancelling}@375a4dd, j0@140b852]
```

**Comment by AkesiSeli** [comment]
You are right, sorry! I misconfigured a binding in #181, I'll release a fix asap!

In the meantime, merry Christmas 🎄🎁🧑🏻‍🎄🦌🎄

**Comment by NicKoehler** [comment]
Merry Christmas to you too 🎄☃️
